#!/bin/sh

printf "Autoindigestion %s\n" `basename $0`


if [ -e /Library/LaunchDaemons/Autoindigestion.plist ]
then
  launchctl unload -F /Library/LaunchDaemons/Autoindigestion.plist
fi


./download_autoingest_tool
if [ "$?" != "0" ]
then
  exit 1
fi
